-- 코드를 입력하세요
# sol 1)
# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO
# WHERE CONCAT(FOOD_TYPE, FAVORITES) IN ( SELECT CONCAT( A.FOOD_TYPE, MAX(A.FAVORITES))
#                     FROM REST_INFO A
#                     GROUP BY A.FOOD_TYPE)
# ORDER BY FOOD_TYPE DESC
        
# sol 2)
# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO
# WHERE (FOOD_TYPE, FAVORITES) IN ( SELECT A.FOOD_TYPE, MAX(A.FAVORITES)
#                                 FROM REST_INFO A
#                                 GROUP BY A.FOOD_TYPE)
# ORDER BY FOOD_TYPE DESC

# sol 3)
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
from (SELECT FOOD_TYPE, 
             REST_ID, 
             REST_NAME,
             FAVORITES,
             ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS THE_RANK
      FROM REST_INFO) A
WHERE A.THE_RANK = 1
ORDER BY A.FOOD_TYPE DESC