-- 코드를 입력하세요
SELECT  DATE_FORMAT(SALES_DATE,'%Y') AS YEAR,
        DATE_FORMAT(SALES_DATE,'%c')+0 AS MONTH,
        COUNT(DISTINCT(B.USER_ID)) AS PUCHASED_USERS,
        ROUND(COUNT(DISTINCT(B.USER_ID)) 
              / (SELECT COUNT(1) FROM USER_INFO WHERE DATE_FORMAT(JOINED, '%Y') = '2021' ),1) AS PUCHASED_RATIO
FROM ONLINE_SALE A
LEFT JOIN  (SELECT *
            FROM USER_INFO
            WHERE DATE_FORMAT(JOINED, '%Y') = '2021' ) B USING (USER_ID)
WHERE B.USER_ID IS NOT NULL
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH

/* SOL BY SG
SELECT  DATE_FORMAT(SALES_DATE,'%Y') AS YEAR,
        DATE_FORMAT(SALES_DATE,'%m') AS MONTH,
        COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,
        ROUND(COUNT(DISTINCT USER_ID)/
        (SELECT  COUNT(USER_ID)
        FROM    USER_INFO B
        WHERE   DATE_FORMAT(JOINED,'%Y')='2021'),1) AS PUCHASED_RATIO
FROM    ONLINE_SALE A
WHERE   1=1
AND     USER_ID IN (SELECT  USER_ID
                    FROM    USER_INFO B
                    WHERE   DATE_FORMAT(JOINED,'%Y')='2021')
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
*/