-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B USING (ANIMAL_ID)
WHERE 1=1
AND A.SEX_UPON_INTAKE LIKE 'Intact%'
AND (LOCATE('Spayed',B.SEX_UPON_OUTCOME) > 0 OR LOCATE('Neutered',B.SEX_UPON_OUTCOME) > 0)
ORDER BY A.ANIMAL_ID ASC
