-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',B.BOARD_ID,'/',B.FILE_ID,B.FILE_NAME,B.FILE_EXT) AS 'FILE_PATH'
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_FILE B USING(BOARD_ID)
WHERE A.VIEWS = (SELECT MAX(C.VIEWS)
              FROM USED_GOODS_BOARD C)
ORDER BY FILE_ID DESC
