-- 코드를 입력하세요
SELECT C.FLAVOR
FROM (  SELECT FLAVOR, RANK() OVER(ORDER BY (A.TOTAL_ORDER+B.JULY_TOTAL_ORDER) DESC) AS RK
        FROM FIRST_HALF A
        JOIN ( SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER 
              FROM JULY 
              GROUP BY FLAVOR ) B USING (FLAVOR)
) C
WHERE C.RK <= 3
ORDER BY C.RK
      
