-- 코드를 입력하세요
# SELECT D.USER_ID, D.NICKNAME, SUM(C.PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD C
# JOIN USED_GOODS_USER D ON D.USER_ID = C.WRITER_ID
# WHERE D.USER_ID IN (SELECT A.USER_ID
#                     FROM USED_GOODS_USER A
#                     JOIN USED_GOODS_BOARD B ON A.USER_ID = B.WRITER_ID
#                     WHERE 1=1
#                     AND B.STATUS = 'DONE'
#                     AND B.PRICE >= 700000)
# GROUP BY D.USER_ID, D.NICKNAME
# ORDER BY TOTAL_SALES ASC

SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_USER B ON B.USER_ID = A.WRITER_ID
WHERE A.STATUS = 'DONE'
GROUP BY B.USER_ID
HAVING SUM(A.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC