-- 코드를 입력하세요
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
JOIN REST_REVIEW B USING (MEMBER_ID)
WHERE MEMBER_ID IN ( SELECT C.MEMBER_ID
                    FROM (  SELECT MEMBER_ID, COUNT(MEMBER_ID), RANK() OVER(ORDER BY COUNT(MEMBER_ID) DESC) AS RK
                            FROM REST_REVIEW 
                            GROUP BY MEMBER_ID
                            ORDER BY RK ASC ) C
                    WHERE C.RK = 1 )
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC



