-- 코드를 입력하세요
SELECT D.AUTHOR_ID, D.AUTHOR_NAME, D.CATEGORY, SUM(D.B_TOTAL_SALES) AS TOTAL_SALES
FROM (  SELECT C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, B.BOOK_ID, SUM(A.SALES)*B.PRICE AS B_TOTAL_SALES
        FROM BOOK_SALES A
        JOIN BOOK B USING (BOOK_ID)
        JOIN AUTHOR C USING (AUTHOR_ID)
        WHERE 1=1
        AND DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
        GROUP BY C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, B.BOOK_ID ) D
GROUP BY D.AUTHOR_ID, D.AUTHOR_NAME, D.CATEGORY
ORDER BY D.AUTHOR_ID ASC, D.CATEGORY DESC