-- 코드를 입력하세요
# SELECT B.PRODUCT_CODE, B.PRICE * A.SALES_AMOUNT AS SALES
# FROM OFFLINE_SALE A
# LEFT JOIN PRODUCT B USING(PRODUCT_ID)
# GROUP BY PRODUCT_CODE
# ORDER BY SALES DESC, B.PRODUCT_CODE

SELECT  PRODUCT_CODE, sum(PRICE * SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE A
LEFT JOIN PRODUCT B USING(PRODUCT_ID)
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, B.PRODUCT_CODE