-- 코드를 입력하세요
SELECT  HISTORY_ID,
        IF( DISCOUNT_YN = 1,
            ROUND(DAILY_FEE * RENT_DAYS * ((100 - DISCOUNT_RATE) / 100)),
            ROUND(DAILY_FEE * RENT_DAYS)
          ) AS FEE
FROM (  SELECT  *,
                RANK() OVER (PARTITION BY HISTORY_ID ORDER BY DISCOUNT_YN DESC, PLAN_ID DESC) AS RK
        FROM (  SELECT  *, 
                        DATEDIFF(END_DATE,START_DATE)+1 AS RENT_DAYS,
                        REPLACE(DURATION_TYPE,'일 이상','')+0 AS TTT,
                        IF(REPLACE(DURATION_TYPE,'일 이상','')+0 <= DATEDIFF(END_DATE,START_DATE)+1, 1, 0) AS DISCOUNT_YN
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
                JOIN CAR_RENTAL_COMPANY_CAR B USING(CAR_ID)
                JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C USING(CAR_TYPE)
                WHERE 1=1
                AND CAR_TYPE = '트럭' ) B ) C
WHERE RK = 1
GROUP BY HISTORY_ID, DAILY_FEE, RENT_DAYS, DISCOUNT_RATE, DISCOUNT_YN
ORDER BY FEE DESC, HISTORY_ID DESC