-- 코드를 입력하세요
SELECT A.APNT_NO, B.PT_NAME, B.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT B USING(PT_NO)
JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
WHERE 1=1
AND DATE_FORMAT(A.APNT_YMD,'%Y-%m-%d') = '2022-04-13'
AND C.MCDP_CD = 'CS'
AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD


