-- 코드를 입력하세요
SELECT DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN CAR_RENTAL_COMPANY_CAR B USING (CAR_ID)
WHERE DATE_FORMAT(START_DATE, '%m') = '10'
AND B.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC
